CREATE TABLE TbCliente (
    PkCodCid INTEGER NOT NULL,
    NomeCid VARCHAR(20) NOT NULL,
    UfCid VARCHAR(2) DEFAULT 'RS'
);

ALTER TABLE TbCliente ADD Email VARCHAR(60);
ALTER TABLE TbCliente RENAME COLUMN Email TO EmailCli;
ALTER TABLE TbCliente MODIFY EmailCli VARCHAR(100);
ALTER TABLE TbCliente DROP COLUMN EmailCli;
ALTER TABLE TbCliente ADD CONSTRAINT TbClientePk PRIMARY KEY(PkCodCid);
